public class SalesforceDeveloper {
    public void myFirstCode() {
        System.debug('Saint Petersburg');
        System.debug('Lord of Rings');
        System.debug('Winter');
    }
    public void myFavourite(){
        Object city = 'Ashgabat';
        Object num = 17;
        String text = num +' and favourite city '+city;
        System.debug(city);
        System.debug(num);
        System.debug(text);
    }
}